import type { Metadata } from "next";
import { Montserrat, Poppins } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const geistMontserrat = Montserrat({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

const geistPoppins = Poppins({
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Azizbek Developer",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,

}: Readonly<{
  children: React.ReactNode;

}>) {

  return (
    <>
    
    <Head>
    <meta name="google-site-verification" content="108d5d5f04b60934" />
  </Head>
    <html lang="en" className="scroll-smooth dark">
      <body
        className={`${geistMontserrat.className} ${geistPoppins.className} antialiased leading-8 overflow-x-hidden dark:bg-darkTheme dark:text-white`}
      >
        {children}
      </body>
    </html>
    </>
  );
}
